#!/bin/bash

DOCSTRING01="%! TEX root = ../main.tex\n"
DOCSTRING02="% this file was automatically created"
DOCSTRING03="% via make by ../scripts/gather_acronyms.tex\n"
DOCSTRING04="\let\oldbaselinestretch=\\\baselinestretch%"
DOCSTRING05="\\\renewcommand{\\\baselinestretch}{1.5}%"
DOCSTRING06="\pagestyle{plain}\n"
DOCSTRING07="\chapter*{Acronyms}"
DOCSTRING08="\label{chapter:acronyms}\n"
DOCSTRING09="\\\begingroup\n\setlength{\parindent}{0pt}\n"
DOCSTRING10="This is a list of alphabetically sorted acronyms and abbreviations used in this work.\n"
DOCSTRING11="\\\endgroup\n"


case $HOSTNAME in
	"beep-boop")
		BASE="/home/quizznor/projects/phd-thesis/Thesis/include/"
		;;
	"rook")
		BASE="/home/quiznor/Projects/phd-thesis/Thesis/include/"
		;;
	*"crcws"*)
		BASE="/cr/users/filip/Thesis/include/"
		;;
	"debian")
		BASE="/home/filip/Desktop/phd-thesis/Thesis/include/"
		;;
	"debian12")
		BASE="/home/filip/Public/phd-thesis/Thesis/include/"
		;;
esac

TARGET="$BASE/acronyms.tex"

echo -e $DOCSTRING01 > "$BASE/acronyms.tex"
echo -e $DOCSTRING02 >> "$BASE/acronyms.tex"
echo -e $DOCSTRING03 >> "$BASE/acronyms.tex"
echo -e $DOCSTRING04 >> "$BASE/acronyms.tex"
echo -e $DOCSTRING05 >> "$BASE/acronyms.tex"
echo -e $DOCSTRING06 >> "$BASE/acronyms.tex"
echo -e $DOCSTRING07 >> "$BASE/acronyms.tex"
echo -e $DOCSTRING08 >> "$BASE/acronyms.tex"
echo -e $DOCSTRING09 >> "$BASE/acronyms.tex"
echo -e $DOCSTRING10 >> "$BASE/acronyms.tex"
echo -e $DOCSTRING11 >> "$BASE/acronyms.tex"

echo -e "\\\begin{acronym}[AAAAA]" >> "$BASE/acronyms.tex" 
echo -e "% some of the plural acros here are clearly bogus" > "$BASE/definitions.tex"

while read line; do
  FIELD=($line)
  SHORT="${FIELD[0]}"
  LONG="${FIELD[@]:1}"

  echo -e \\\\"acro{$SHORT}{$LONG}" >> "$BASE/acronyms.tex"
  
  if [ "$SHORT" = "T2" ]; then continue; fi
  if [ "$SHORT" = "T3" ]; then continue; fi

  echo -e \\\\"newcommand{"\\\\"$SHORT}{"\\\\"ac{$SHORT}\\\\xspace}" >> "$BASE/definitions.tex"
  
  if [ "$SHORT" = "QFT" ]; then
	  echo -e \\\\"acrodefplural{QFT}{Quantum Field Theories}" >> "$BASE/definitions.tex"
  fi

  echo -e \\\\"newcommand{"\\\\"$SHORT"s}{\\\\"acp{$SHORT}\\\\xspace}" >> "$BASE/definitions.tex"


done < "$BASE/acronyms.source"
echo -e "\\\end{acronym}\n" >> "$BASE/acronyms.tex"
echo -e "\let\\\baselinestretch=\oldbaselinestretch" >> "$BASE/acronyms.tex"
echo -e "\\input{include/definitions.tex}" >> "$BASE/acronyms.tex"
