#!/bin/bash

DOCSTRING1="%! TEX root = ../main.tex\n"
DOCSTRING2="% this file was automatically created"
DOCSTRING3="% via make by ../scripts/gather_chapters\n"

case $HOSTNAME in
    "beep-boop")
        TARGET="/home/quizznor/projects/phd-thesis/Thesis/chap/chapters.tex"
        ;;
    "rook")
        TARGET="/home/quizznor/Projects/phd-thesis/Thesis/chap/chapters.tex"
        ;;
    *"crcws"*)
        TARGET="/cr/users/filip/Thesis/chap/chapters.tex"
        ;;
    "debian")
	TARGET="/home/filip/Desktop/phd-thesis/Thesis/chap/chapters.tex"
	;;
    "debian12")
	TARGET="/home/filip/Public/phd-thesis/Thesis/chap/chapters.tex"
	;;
esac

echo -e $DOCSTRING1 > "$TARGET"
echo -e $DOCSTRING2 >> "$TARGET"
echo -e $DOCSTRING3 >> "$TARGET"
ls chap/*-*.tex | sed -e 's/\(.*\)/\\include{\1}/' >> "$TARGET"
