#!/bin/bash

DOCSTRING1="%! TEX root = ../main.tex\n"
DOCSTRING2="% this file was automatically created"
DOCSTRING3="% via make by ../scripts/gather_appendices\n"
DOCSTRING4="\\\titleformat{\section}[display]{\\\normalfont\\\bfseries\\\Large}{}{0.3cm}{\\\vspace{-0.7cm}\sc{\\\thesection}\hspace{0.3cm}\\\sc{#1}}\n"
DOCSTRING5="\\\appendix"

case $HOSTNAME in
    "beep-boop")
        TARGET="/home/quizznor/projects/phd-thesis/Thesis/app/appendix.tex"
        ;;
    "rook")
        TARGET="/home/quizznor/Projects/phd-thesis/Thesis/app/appendix.tex"
        ;;
    *"crcws"*)
        TARGET="/cr/users/filip/Thesis/app/appendix.tex"
        ;;
    "debian")
	TARGET="/home/filip/Desktop/phd-thesis/Thesis/app/appendix.tex"
	;;
    "debian12")
	TARGET="/home/filip/Public/phd-thesis/Thesis/app/appendix.tex"
esac

echo -e $DOCSTRING1 > $TARGET
echo -e $DOCSTRING2 >> $TARGET
echo -e $DOCSTRING3 >> $TARGET
echo -e $DOCSTRING4 >> $TARGET
echo -e $DOCSTRING5 >> $TARGET
ls app/*-*.tex | sed -e 's/\(.*\)/\\include{\1}/' >> $TARGET
